app/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
]

app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('blog/', include('blog.urls')),
    path('', index),
    ]

app/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

app/blog/models.py
from django.db import models

# Create your models here.

app/common/models.py
from django.db import models

# Create your models here.

app/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    # votes를 누르면 선택된 각 choice의 아이디에 저장시켜야함


    def __str__(self):
        return self.choice_text

app/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    # localhost:8000/blog
    # 1. config.urls에서 blog.urls를 include, path는 'blog/'를 사용
    # 2. blog app내에 urls모듈을 생성하고 이 view를 위 URL과 연결되도록 설정
    # 3. localhost:8000/blog에서 blog index가 출력되는지 확

    return render(request, 'blog/index.html')

app/common/views.py
from django.shortcuts import render

def index(request):
    # 1. common app내에 templates/common/iondex.html파일 생성
    # 2. 해당 파일에서 /blog로의 링크, /polls/로의 링크(a태그)enro todtjd
    # 3. installed_apps에 common을 추가
    # 4. config.urls에서 이 view를 바로 연결 (include 사용 x)
    return render(request, 'common/index.html')

app/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question, Choice
from django.template import loader


def index(request):
    # 최신 질문들을 정리하는데 pub_date를 역순으로 0~4번째까지
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # output을 "질문명, 질문내용" 으로 저장
    context = {
        'latest_question_list': latest_question_list,
    }

    template = loader.get_template('polls/index.html')
    html = template.render(context, request)
    # output을 웹 응답으로 송신 및 출력
    return render(request, 'polls/index.html', context)

def custom_get_object_or_404(model, **kwargs):
    try:
        return model.objects.get(**kwargs)
    except model.DoesNotExist:
        raise Http404()

def detail(request, question_id):
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")

    question = custom_get_object_or_404(Question, id=question_id)
    context = {
        'question': question,
    }
    # return HttpResponse("You're looking at question %s." % question_id)
    return render(request, 'polls/detail.html', context)

def results(request, question_id):
    # question_id 해당하는 Question 인스턴스 전달
    # 템플릿 (polls/templates/polls/results.html
    # Question의 question_tesxt를 보여주고
    # Question에 연결된 Choice목록과 vote수를 보여준다
    # {% for %} loop구문과
    # question.choice_set.all 을 사용

    question = Question.objects.get(id=question_id)
    # choice_id = request.POST['choice']
    # choice = Choice.objects.get(id=choice_id)
    # choice_text = choice.choice_text
    # choice_votes = choice.votes

    context = {
        'question' : question,
        # 'choice' : choice,
        # 'choice_text' : choice_text,
        # 'choice_votes' : choice_votes
    }

    return render(request, 'polls/results.html', context)

def vote(request, question_id):

    # print('request.get : ', request.GET)
    # print('request.POST : ', request.POST)
    # 선택한 choice의 choice_text와 id값을 갖는 문자열 생성
    question = Question.objects.get(id=question_id)
    question_text = question.question_text

    choice_id = request.POST['choice']
    choice = Choice.objects.get(id=choice_id)
    choice_text = choice.choice_text

    choice.votes += 1
    choice.save()

    choice_votes = choice.votes

    result = 'question_text : {}, choice_text: {}, choice.id: {}, choice_votes: {}'.format(
        question_text,
        choice_text,
        choice_id,
        choice_votes,
    )
    url = '/polls/{}/results/'.format(question_id)
    return HttpResponseRedirect(url)

    url = reverse('polls:results', args=[question_id])
    return HttpResponseRedirect(url)

app/blog/templates/blog/index.html
BLOG INDEX

app/common/templates/common/index.html
   <li> <a href="{% url 'polls:index' %}">Polls index</a></li>
    <li><a href="{% url 'blog:index' %}">Blog index</a></li>

app/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %} <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question_id=question.id %}" method="post">
    {% csrf_token %}
    <!--
        여기가 Question detail페이지이며, question키에 해당하는 Question인스턴스가 할당되어 있음
        현재 Question에 속하는 Choice목록은 question.choice_set.all로 QuerySet을 얻어낼 수 있으며,
        for 구문으로 QuerySet을 순회한다.
    -->
    {% for choice in question.choice_set.all %}
    <!--
        각 Loop (매 Loop의 아이템: Choice인스턴스)
        마다 radio input과 label을 만들어줌
    -->
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}

    <!-- 전송 버튼 -->
    <button type="submit">Vote</button>
</form>

app/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li>
            <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available</p>
{% endif %}

app/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}

    <li>{{ choice.choice_text }} (votes: {{ choice.votes }})</li>
{% endfor %}
</ul>